[[Triangle]]
arch = "aarch64"
git-tree-sha1 = "1f0055b1638641b4b1be0482080f084cb4a9b60f"
os = "macos"

    [[Triangle.download]]
    sha256 = "89cb9162d1e3d1e7a91e07ff3be37df524e0550650c9fcdd673e312fdd0fd317"
    url = "https://github.com/JuliaBinaryWrappers/Triangle_jll.jl/releases/download/Triangle-v1.6.3+1/Triangle.v1.6.3.aarch64-apple-darwin.tar.gz"
[[Triangle]]
arch = "aarch64"
git-tree-sha1 = "a1b6811877ef0ea2509c784908388de777294982"
libc = "glibc"
os = "linux"

    [[Triangle.download]]
    sha256 = "5be2d10ee1251ae8769fceef0bf57ee0307c7cac4e143fdae6901cd76604c253"
    url = "https://github.com/JuliaBinaryWrappers/Triangle_jll.jl/releases/download/Triangle-v1.6.3+1/Triangle.v1.6.3.aarch64-linux-gnu.tar.gz"
[[Triangle]]
arch = "aarch64"
git-tree-sha1 = "5370e7a4d0a580ffd0e2c13c31aca1fe2142fe35"
libc = "musl"
os = "linux"

    [[Triangle.download]]
    sha256 = "52a8013e5ca1cf745ede6a054e51b87449dd270f1d6f2bdeb0b80b1f34525168"
    url = "https://github.com/JuliaBinaryWrappers/Triangle_jll.jl/releases/download/Triangle-v1.6.3+1/Triangle.v1.6.3.aarch64-linux-musl.tar.gz"
[[Triangle]]
arch = "aarch64"
git-tree-sha1 = "47a878a379996146b5f2828d44bf8eb8a3176ea5"
os = "freebsd"

    [[Triangle.download]]
    sha256 = "3ad01d9516a87e2f50f63fb3e2aa169e8ea117baeba49bde12c89f5317c2d432"
    url = "https://github.com/JuliaBinaryWrappers/Triangle_jll.jl/releases/download/Triangle-v1.6.3+1/Triangle.v1.6.3.aarch64-unknown-freebsd.tar.gz"
[[Triangle]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d6828a8390477f1c2d75329d491faa40772df501"
libc = "glibc"
os = "linux"

    [[Triangle.download]]
    sha256 = "1c4a1a5c9e4f3b28ab90c0aa22aa876ea0cb8a3bf29fe19a12bf019a0cea9c20"
    url = "https://github.com/JuliaBinaryWrappers/Triangle_jll.jl/releases/download/Triangle-v1.6.3+1/Triangle.v1.6.3.armv6l-linux-gnueabihf.tar.gz"
[[Triangle]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3792701f0d1f023af744ff143725116522a940c7"
libc = "musl"
os = "linux"

    [[Triangle.download]]
    sha256 = "4494942128d32a6c72a22b69ca5ad59bd09cf3bfac7069d2b99d4755d621d792"
    url = "https://github.com/JuliaBinaryWrappers/Triangle_jll.jl/releases/download/Triangle-v1.6.3+1/Triangle.v1.6.3.armv6l-linux-musleabihf.tar.gz"
[[Triangle]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b565d0ab55aaaaa0d113ecebd6a919a68b64b4d6"
libc = "glibc"
os = "linux"

    [[Triangle.download]]
    sha256 = "9ae8b3442bbd18c0c2d62f4a4ce887b652a13b9c6e70215c7b036f3ce20aae1f"
    url = "https://github.com/JuliaBinaryWrappers/Triangle_jll.jl/releases/download/Triangle-v1.6.3+1/Triangle.v1.6.3.armv7l-linux-gnueabihf.tar.gz"
[[Triangle]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6423d9eff69924372e5417c74fb2dc32cb5b0ae0"
libc = "musl"
os = "linux"

    [[Triangle.download]]
    sha256 = "5c64475aa3d184e1b024e6171070f77bb07c53e93bee7ba07b8d88a80d4ff3ff"
    url = "https://github.com/JuliaBinaryWrappers/Triangle_jll.jl/releases/download/Triangle-v1.6.3+1/Triangle.v1.6.3.armv7l-linux-musleabihf.tar.gz"
[[Triangle]]
arch = "i686"
git-tree-sha1 = "7c90328626eaa3256bd9420dc86e23651c202feb"
libc = "glibc"
os = "linux"

    [[Triangle.download]]
    sha256 = "e91aeb48320bc988c5aca52c4d7f679797fb52da6257b46cf0b0b391ef7ab2d2"
    url = "https://github.com/JuliaBinaryWrappers/Triangle_jll.jl/releases/download/Triangle-v1.6.3+1/Triangle.v1.6.3.i686-linux-gnu.tar.gz"
[[Triangle]]
arch = "i686"
git-tree-sha1 = "55a7a5d8b6544cb056423c59cbd9c7f7ac078ef8"
libc = "musl"
os = "linux"

    [[Triangle.download]]
    sha256 = "c9f8acfc9bb2621855dd034ea95aa3cd19876971005ff5e13b12a4a5eed5cfd5"
    url = "https://github.com/JuliaBinaryWrappers/Triangle_jll.jl/releases/download/Triangle-v1.6.3+1/Triangle.v1.6.3.i686-linux-musl.tar.gz"
[[Triangle]]
arch = "i686"
git-tree-sha1 = "748ac40e567c685f95fced5d1682f359a85c4941"
os = "windows"

    [[Triangle.download]]
    sha256 = "bcaeba95bdfcaa99cd88a0a1818ee73eb8bd7952ef591b0ee689e76d21678710"
    url = "https://github.com/JuliaBinaryWrappers/Triangle_jll.jl/releases/download/Triangle-v1.6.3+1/Triangle.v1.6.3.i686-w64-mingw32.tar.gz"
[[Triangle]]
arch = "powerpc64le"
git-tree-sha1 = "3b0c5afb3979d86cec0bfc80016b51fdc76ed671"
libc = "glibc"
os = "linux"

    [[Triangle.download]]
    sha256 = "964ef607abc629094ef4785ab058630abe32b70741a69c8ba05d64061258bca0"
    url = "https://github.com/JuliaBinaryWrappers/Triangle_jll.jl/releases/download/Triangle-v1.6.3+1/Triangle.v1.6.3.powerpc64le-linux-gnu.tar.gz"
[[Triangle]]
arch = "riscv64"
git-tree-sha1 = "604109632cc72980af2dbf9af3a5f9add6482806"
libc = "glibc"
os = "linux"

    [[Triangle.download]]
    sha256 = "a2c577b3db43cf68b02e50334ec4b594c8761865d7d8f4d336b98708e2521420"
    url = "https://github.com/JuliaBinaryWrappers/Triangle_jll.jl/releases/download/Triangle-v1.6.3+1/Triangle.v1.6.3.riscv64-linux-gnu.tar.gz"
[[Triangle]]
arch = "x86_64"
git-tree-sha1 = "393924221478b6cfeabb60b0fa4e68abc63f3f53"
os = "macos"

    [[Triangle.download]]
    sha256 = "2938a4508e371b6cebd5ed20306ef15485226df69657cdfa31c9ec7f7a55910e"
    url = "https://github.com/JuliaBinaryWrappers/Triangle_jll.jl/releases/download/Triangle-v1.6.3+1/Triangle.v1.6.3.x86_64-apple-darwin.tar.gz"
[[Triangle]]
arch = "x86_64"
git-tree-sha1 = "6f6a04b86c8ddb40556920b88607e428314cb5bd"
libc = "glibc"
os = "linux"

    [[Triangle.download]]
    sha256 = "cece77f28d3f9e9e767741a921da5836faafe0db2547a37c651ac59bb9bb4469"
    url = "https://github.com/JuliaBinaryWrappers/Triangle_jll.jl/releases/download/Triangle-v1.6.3+1/Triangle.v1.6.3.x86_64-linux-gnu.tar.gz"
[[Triangle]]
arch = "x86_64"
git-tree-sha1 = "3cfbd7ec36c632d9c6d8adad8ce316e3bb139694"
libc = "musl"
os = "linux"

    [[Triangle.download]]
    sha256 = "5a4aa613812c61706d90d08f44116c7b1e5027a7b6dd3110b83833024e41d9f1"
    url = "https://github.com/JuliaBinaryWrappers/Triangle_jll.jl/releases/download/Triangle-v1.6.3+1/Triangle.v1.6.3.x86_64-linux-musl.tar.gz"
[[Triangle]]
arch = "x86_64"
git-tree-sha1 = "a920e35c67e3c46926f09d9d0d84459c6eb632fc"
os = "freebsd"

    [[Triangle.download]]
    sha256 = "5adf40da26738d769f571117a1d13183cfbc8be9781e768315e7b0a66c1084eb"
    url = "https://github.com/JuliaBinaryWrappers/Triangle_jll.jl/releases/download/Triangle-v1.6.3+1/Triangle.v1.6.3.x86_64-unknown-freebsd.tar.gz"
[[Triangle]]
arch = "x86_64"
git-tree-sha1 = "604654949418e0e8f44a226c0e7cfaba086179e4"
os = "windows"

    [[Triangle.download]]
    sha256 = "e1bc1cb7c16fe7bbba2fa17280155cfaa7588fc4e880676685149067b7a46467"
    url = "https://github.com/JuliaBinaryWrappers/Triangle_jll.jl/releases/download/Triangle-v1.6.3+1/Triangle.v1.6.3.x86_64-w64-mingw32.tar.gz"
