[[Triangle]]
arch = "aarch64"
git-tree-sha1 = "dab715b2fb20dfb5c761cc91a4f0ce80fc28d9b2"
os = "macos"

    [[Triangle.download]]
    sha256 = "32c8dc9e92b5fd203101b12e418681b37209151022ef051fc422fe1274e6648d"
    url = "https://github.com/JuliaBinaryWrappers/Triangle_jll.jl/releases/download/Triangle-v1.6.3+2/Triangle.v1.6.3.aarch64-apple-darwin.tar.gz"
[[Triangle]]
arch = "aarch64"
git-tree-sha1 = "d203943c5acbe695a1554b869c6544ae9c101e94"
libc = "glibc"
os = "linux"

    [[Triangle.download]]
    sha256 = "80111e9fae2a0a117fe1290ce606a6f86cb7eb07fad7ddfda4b416fef19c2c87"
    url = "https://github.com/JuliaBinaryWrappers/Triangle_jll.jl/releases/download/Triangle-v1.6.3+2/Triangle.v1.6.3.aarch64-linux-gnu.tar.gz"
[[Triangle]]
arch = "aarch64"
git-tree-sha1 = "f3e51ff92226edc5156f4d7848447f78fe96c376"
libc = "musl"
os = "linux"

    [[Triangle.download]]
    sha256 = "1a55b64de95e1544f5bc4bd546409d7f33379fd87064877ea306a8820426707d"
    url = "https://github.com/JuliaBinaryWrappers/Triangle_jll.jl/releases/download/Triangle-v1.6.3+2/Triangle.v1.6.3.aarch64-linux-musl.tar.gz"
[[Triangle]]
arch = "aarch64"
git-tree-sha1 = "8be5d42cc9a291631f3665ead958aba46470e423"
os = "freebsd"

    [[Triangle.download]]
    sha256 = "70db874541e624f9e2bc3cb192b8f53cdc3d3f1d1bd98f2d8c3d86a5c147e15a"
    url = "https://github.com/JuliaBinaryWrappers/Triangle_jll.jl/releases/download/Triangle-v1.6.3+2/Triangle.v1.6.3.aarch64-unknown-freebsd.tar.gz"
[[Triangle]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "01a3c743f85520632d8acc8877496c38e2838f5b"
libc = "glibc"
os = "linux"

    [[Triangle.download]]
    sha256 = "1a899864fd2f1c13d8c5d231c70f74022a05556c7c88a8fcb14a793396893c40"
    url = "https://github.com/JuliaBinaryWrappers/Triangle_jll.jl/releases/download/Triangle-v1.6.3+2/Triangle.v1.6.3.armv6l-linux-gnueabihf.tar.gz"
[[Triangle]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4c2159f7aec50e636136e407b2bc08e19ccd095c"
libc = "musl"
os = "linux"

    [[Triangle.download]]
    sha256 = "9acd2be61ec61dc735bed71dac27cb623c688dfef2fc4bf822e35e62628286d3"
    url = "https://github.com/JuliaBinaryWrappers/Triangle_jll.jl/releases/download/Triangle-v1.6.3+2/Triangle.v1.6.3.armv6l-linux-musleabihf.tar.gz"
[[Triangle]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "565749acd8c08e2ddd0ee90d8717d4f64c922ad2"
libc = "glibc"
os = "linux"

    [[Triangle.download]]
    sha256 = "1d598830f2413556af3a9268bed8b37b4407a3e6669e54a9ede00ac93cd55735"
    url = "https://github.com/JuliaBinaryWrappers/Triangle_jll.jl/releases/download/Triangle-v1.6.3+2/Triangle.v1.6.3.armv7l-linux-gnueabihf.tar.gz"
[[Triangle]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1a548e8717d6ebb2ce52e169ca036c3516482291"
libc = "musl"
os = "linux"

    [[Triangle.download]]
    sha256 = "91b941cc61537136b23afd18ba43c1d25ed14c51375f556d0d508abc0f37f3a0"
    url = "https://github.com/JuliaBinaryWrappers/Triangle_jll.jl/releases/download/Triangle-v1.6.3+2/Triangle.v1.6.3.armv7l-linux-musleabihf.tar.gz"
[[Triangle]]
arch = "i686"
git-tree-sha1 = "71002b008c0dad9dad939e895e3121176feed5dd"
libc = "glibc"
os = "linux"

    [[Triangle.download]]
    sha256 = "9566031d8572a8e5cc18d149c2a22f5340517e17ade9bb8ee3e86871a5fe2a2b"
    url = "https://github.com/JuliaBinaryWrappers/Triangle_jll.jl/releases/download/Triangle-v1.6.3+2/Triangle.v1.6.3.i686-linux-gnu.tar.gz"
[[Triangle]]
arch = "i686"
git-tree-sha1 = "3762ba0a57c34af45551da7fc8c182c06be55d34"
libc = "musl"
os = "linux"

    [[Triangle.download]]
    sha256 = "8dc7c2a1029ebc40f0bada67bd443eaa7285ea026d5f8b1e3fd28b9c5b21af26"
    url = "https://github.com/JuliaBinaryWrappers/Triangle_jll.jl/releases/download/Triangle-v1.6.3+2/Triangle.v1.6.3.i686-linux-musl.tar.gz"
[[Triangle]]
arch = "i686"
git-tree-sha1 = "28690437d15ee6124ec484a78cf20d7678026e71"
os = "windows"

    [[Triangle.download]]
    sha256 = "fc39eef1b22ae88d29e0a32f6b00be8fe5445ef3f0e8f4c55d9cc914b6923d2b"
    url = "https://github.com/JuliaBinaryWrappers/Triangle_jll.jl/releases/download/Triangle-v1.6.3+2/Triangle.v1.6.3.i686-w64-mingw32.tar.gz"
[[Triangle]]
arch = "powerpc64le"
git-tree-sha1 = "8ab63cff547bff5f639f14cb16d4cad5829bcbf9"
libc = "glibc"
os = "linux"

    [[Triangle.download]]
    sha256 = "598abcbfe9ac7d2893d8c8eb108e524a39a6added9a6c94a4daad06e308df802"
    url = "https://github.com/JuliaBinaryWrappers/Triangle_jll.jl/releases/download/Triangle-v1.6.3+2/Triangle.v1.6.3.powerpc64le-linux-gnu.tar.gz"
[[Triangle]]
arch = "riscv64"
git-tree-sha1 = "aeab139643f3fc4bd62a659e153523c0fcdfbab1"
libc = "glibc"
os = "linux"

    [[Triangle.download]]
    sha256 = "922234871aeac342c7c7ac6084e6ae7b61207f63076a69a411ce8547dc8f7bc4"
    url = "https://github.com/JuliaBinaryWrappers/Triangle_jll.jl/releases/download/Triangle-v1.6.3+2/Triangle.v1.6.3.riscv64-linux-gnu.tar.gz"
[[Triangle]]
arch = "x86_64"
git-tree-sha1 = "40ff29d688dfc4958d342b3d2ec89c65b53cfc83"
os = "macos"

    [[Triangle.download]]
    sha256 = "e74fe98aa7c626067838559c795ba89f7259aa3de1436e9784237f0623455bbe"
    url = "https://github.com/JuliaBinaryWrappers/Triangle_jll.jl/releases/download/Triangle-v1.6.3+2/Triangle.v1.6.3.x86_64-apple-darwin.tar.gz"
[[Triangle]]
arch = "x86_64"
git-tree-sha1 = "e3e99b5cad2928b5834d13104e74c61db4700c61"
libc = "glibc"
os = "linux"

    [[Triangle.download]]
    sha256 = "6380168d24e7c907ae6e0e7b7f3a625e4815b3babffbc0a77805a174fe2fb634"
    url = "https://github.com/JuliaBinaryWrappers/Triangle_jll.jl/releases/download/Triangle-v1.6.3+2/Triangle.v1.6.3.x86_64-linux-gnu.tar.gz"
[[Triangle]]
arch = "x86_64"
git-tree-sha1 = "870ed36cc0a4951ea2ba01700c5c5c5e347394d9"
libc = "musl"
os = "linux"

    [[Triangle.download]]
    sha256 = "556c90d73b12cf02108f6cf59a2617056c87ced9fb1609372cabe49a3149281d"
    url = "https://github.com/JuliaBinaryWrappers/Triangle_jll.jl/releases/download/Triangle-v1.6.3+2/Triangle.v1.6.3.x86_64-linux-musl.tar.gz"
[[Triangle]]
arch = "x86_64"
git-tree-sha1 = "dfa9070dc2c5c2d51788b6f9220d9734dc9e2696"
os = "freebsd"

    [[Triangle.download]]
    sha256 = "4015b916277c8a766641cdd3fc3ad0d20794ea59aaeb3241ea029501e7720f36"
    url = "https://github.com/JuliaBinaryWrappers/Triangle_jll.jl/releases/download/Triangle-v1.6.3+2/Triangle.v1.6.3.x86_64-unknown-freebsd.tar.gz"
[[Triangle]]
arch = "x86_64"
git-tree-sha1 = "41289b462d692d7a68556f9e2ef31e12a7ec104c"
os = "windows"

    [[Triangle.download]]
    sha256 = "5a362158fe9ea3a8ce4d08b31fbe0d0b0884c253ab18fa7b37da8d2e7a5428a5"
    url = "https://github.com/JuliaBinaryWrappers/Triangle_jll.jl/releases/download/Triangle-v1.6.3+2/Triangle.v1.6.3.x86_64-w64-mingw32.tar.gz"
